apiVersion: v1
kind: Secret
metadata:
    name: authorizer-secret
    namespace: dev-authorizer
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:4SujSE2h4J+Affsq,iv:4/yZqNRoNIcGraeftA948dbVLJ6RN+HxCpCWgFst1ng=,tag:UM15A61PoDrn9Wd7+NxJ1g==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:tsNt9HIgkXqV3t2++3MRyCyb,iv:qzvJfqRRgKXrN5fAkuZQ+C+0bY8jmrWEpIP1m2DSqeM=,tag:YcNisUW7RK2kjlu0uvX7YQ==,type:str]
sops:
    age:
        - recipient: age1zepgztvuxsysncygjteppy7jsdglmalfvx48p4ten06ndaycfs3qsgt3m9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbHFWbVJsdjg3eC9WeW94
            dzJMMTlEbDFhM2t3NHRXVFZhSWZpUDFHQkVJCnlnZFVCdlp3THNodnpNNVJDU09w
            MlVjVTc4blNqenlQa1U1T0lSS3ZiZ2sKLS0tIGdCejhoVFVLME13bG1vN1JMc09R
            MFNQTXNHVGo4ZXIrU09uRlQ2NkpvZzgKOA6ySP+6nV70ymftP7kC9h6TqZubN/4l
            ljyhoZbYUJz6vrGwEuRKtZynLKMykEiwH3aBwti1q87mlFJAb6CMJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T18:06:09Z"
    mac: ENC[AES256_GCM,data:X07T2TgR3uS7CJshIE9pDsjqMvuhseIxDkU10BtvmhMnlNv5MBNyJ4ZwWAbAeHb6C0FRCgPiWJzyD8PiheaU0piyS6H3Q5a0y/yS1IwZyB4SYpcqqbEn+O3l/wwManMy59CU4LA0hJ2ghVj9BYWG19puABlSSlJujrBpgF8126E=,iv:xU85lEsLFNmdrSmdt4Xp0T++052FTgQQY5Mrwuc0xyI=,tag:XdnjaB/QeblQQKOpuJS+hA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
